server:
  port: 8080

spring:
  application:
    name: calendar-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:practicebank}
    username: ${DB_USERNAME:practicebank}
    password: ${DB_PASSWORD:practicebank}
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
  mapper-locations: classpath*:mappers/**/*.xml
